// Generated by scripts/generate-event-photos.mjs. Do not edit manually.
export const eventPhotos = [
  {
    "id": "event-photo-1",
    "src": "/images/events/thumbs/20241116_140546.webp",
    "originalSrc": "/images/events/20241116_140546.jpg",
    "alt": "Quant-A-Maze event photo 1",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-2",
    "src": "/images/events/thumbs/20241116_140546(0).webp",
    "originalSrc": "/images/events/20241116_140546(0).jpg",
    "alt": "Quant-A-Maze event photo 2",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-3",
    "src": "/images/events/thumbs/20241116_140549.webp",
    "originalSrc": "/images/events/20241116_140549.jpg",
    "alt": "Quant-A-Maze event photo 3",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-4",
    "src": "/images/events/thumbs/20241116_140550.webp",
    "originalSrc": "/images/events/20241116_140550.jpg",
    "alt": "Quant-A-Maze event photo 4",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-5",
    "src": "/images/events/thumbs/20241116_140551.webp",
    "originalSrc": "/images/events/20241116_140551.jpg",
    "alt": "Quant-A-Maze event photo 5",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-6",
    "src": "/images/events/thumbs/20241116_140554.webp",
    "originalSrc": "/images/events/20241116_140554.jpg",
    "alt": "Quant-A-Maze event photo 6",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-7",
    "src": "/images/events/thumbs/20241116_140555.webp",
    "originalSrc": "/images/events/20241116_140555.jpg",
    "alt": "Quant-A-Maze event photo 7",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-8",
    "src": "/images/events/thumbs/20241116_140600.webp",
    "originalSrc": "/images/events/20241116_140600.jpg",
    "alt": "Quant-A-Maze event photo 8",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-9",
    "src": "/images/events/thumbs/20241116_140601.webp",
    "originalSrc": "/images/events/20241116_140601.jpg",
    "alt": "Quant-A-Maze event photo 9",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-10",
    "src": "/images/events/thumbs/20241116_140604.webp",
    "originalSrc": "/images/events/20241116_140604.jpg",
    "alt": "Quant-A-Maze event photo 10",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-11",
    "src": "/images/events/thumbs/20241116_140620.webp",
    "originalSrc": "/images/events/20241116_140620.jpg",
    "alt": "Quant-A-Maze event photo 11",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-12",
    "src": "/images/events/thumbs/20241116_140621.webp",
    "originalSrc": "/images/events/20241116_140621.jpg",
    "alt": "Quant-A-Maze event photo 12",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-13",
    "src": "/images/events/thumbs/20241116_140623.webp",
    "originalSrc": "/images/events/20241116_140623.jpg",
    "alt": "Quant-A-Maze event photo 13",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-14",
    "src": "/images/events/thumbs/20241116_140625.webp",
    "originalSrc": "/images/events/20241116_140625.jpg",
    "alt": "Quant-A-Maze event photo 14",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-15",
    "src": "/images/events/thumbs/20241116_140626.webp",
    "originalSrc": "/images/events/20241116_140626.jpg",
    "alt": "Quant-A-Maze event photo 15",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-16",
    "src": "/images/events/thumbs/20241116_140627.webp",
    "originalSrc": "/images/events/20241116_140627.jpg",
    "alt": "Quant-A-Maze event photo 16",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-17",
    "src": "/images/events/thumbs/20241116_140628.webp",
    "originalSrc": "/images/events/20241116_140628.jpg",
    "alt": "Quant-A-Maze event photo 17",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-18",
    "src": "/images/events/thumbs/20241116_140634.webp",
    "originalSrc": "/images/events/20241116_140634.jpg",
    "alt": "Quant-A-Maze event photo 18",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-19",
    "src": "/images/events/thumbs/20241116_140636.webp",
    "originalSrc": "/images/events/20241116_140636.jpg",
    "alt": "Quant-A-Maze event photo 19",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-20",
    "src": "/images/events/thumbs/20241116_140723.webp",
    "originalSrc": "/images/events/20241116_140723.jpg",
    "alt": "Quant-A-Maze event photo 20",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-21",
    "src": "/images/events/thumbs/20241116_140724.webp",
    "originalSrc": "/images/events/20241116_140724.jpg",
    "alt": "Quant-A-Maze event photo 21",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-22",
    "src": "/images/events/thumbs/20241116_140725.webp",
    "originalSrc": "/images/events/20241116_140725.jpg",
    "alt": "Quant-A-Maze event photo 22",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-23",
    "src": "/images/events/thumbs/20241116_140725(0).webp",
    "originalSrc": "/images/events/20241116_140725(0).jpg",
    "alt": "Quant-A-Maze event photo 23",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-24",
    "src": "/images/events/thumbs/20241116_140726.webp",
    "originalSrc": "/images/events/20241116_140726.jpg",
    "alt": "Quant-A-Maze event photo 24",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-25",
    "src": "/images/events/thumbs/20241116_140823.webp",
    "originalSrc": "/images/events/20241116_140823.jpg",
    "alt": "Quant-A-Maze event photo 25",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-26",
    "src": "/images/events/thumbs/20241116_140830.webp",
    "originalSrc": "/images/events/20241116_140830.jpg",
    "alt": "Quant-A-Maze event photo 26",
    "width": 4000,
    "height": 2252
  },
  {
    "id": "event-photo-27",
    "src": "/images/events/thumbs/Copy%20of%20IMG20241114152358_01.webp",
    "originalSrc": "/images/events/Copy%20of%20IMG20241114152358_01.jpg",
    "alt": "Quant-A-Maze event photo 27",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "event-photo-28",
    "src": "/images/events/thumbs/Copy%20of%20IMG20241114152600.webp",
    "originalSrc": "/images/events/Copy%20of%20IMG20241114152600.jpg",
    "alt": "Quant-A-Maze event photo 28",
    "width": 3072,
    "height": 4096
  },
  {
    "id": "event-photo-29",
    "src": "/images/events/thumbs/Copy%20of%20WhatsApp%20Image%202024-11-15%20at%2004.17.42_a5433a01.webp",
    "originalSrc": "/images/events/Copy%20of%20WhatsApp%20Image%202024-11-15%20at%2004.17.42_a5433a01.jpg",
    "alt": "Quant-A-Maze event photo 29",
    "width": 721,
    "height": 1280
  },
  {
    "id": "event-photo-30",
    "src": "/images/events/thumbs/Copy%20of%20WhatsApp%20Image%202024-11-15%20at%2012.53.41_2be0eb49.webp",
    "originalSrc": "/images/events/Copy%20of%20WhatsApp%20Image%202024-11-15%20at%2012.53.41_2be0eb49.jpg",
    "alt": "Quant-A-Maze event photo 30",
    "width": 1152,
    "height": 864
  },
  {
    "id": "event-photo-31",
    "src": "/images/events/thumbs/Copy%20of%20WhatsApp%20Image%202024-11-16%20at%2009.56.02_1059f7e2.webp",
    "originalSrc": "/images/events/Copy%20of%20WhatsApp%20Image%202024-11-16%20at%2009.56.02_1059f7e2.jpg",
    "alt": "Quant-A-Maze event photo 31",
    "width": 4096,
    "height": 3072
  },
  {
    "id": "event-photo-32",
    "src": "/images/events/thumbs/IMG-20241114-WA0294.webp",
    "originalSrc": "/images/events/IMG-20241114-WA0294.jpg",
    "alt": "Quant-A-Maze event photo 32",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-33",
    "src": "/images/events/thumbs/IMG-20241114-WA0296.webp",
    "originalSrc": "/images/events/IMG-20241114-WA0296.jpg",
    "alt": "Quant-A-Maze event photo 33",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-34",
    "src": "/images/events/thumbs/IMG-20241114-WA0530(1).webp",
    "originalSrc": "/images/events/IMG-20241114-WA0530(1).jpg",
    "alt": "Quant-A-Maze event photo 34",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-35",
    "src": "/images/events/thumbs/IMG-20241116-WA0417.webp",
    "originalSrc": "/images/events/IMG-20241116-WA0417.jpg",
    "alt": "Quant-A-Maze event photo 35",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-36",
    "src": "/images/events/thumbs/IMG-20241116-WA0433.webp",
    "originalSrc": "/images/events/IMG-20241116-WA0433.jpg",
    "alt": "Quant-A-Maze event photo 36",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-37",
    "src": "/images/events/thumbs/IMG-20241116-WA0461.webp",
    "originalSrc": "/images/events/IMG-20241116-WA0461.jpg",
    "alt": "Quant-A-Maze event photo 37",
    "width": 3024,
    "height": 4032
  },
  {
    "id": "event-photo-38",
    "src": "/images/events/thumbs/IMG-20241116-WA0463.webp",
    "originalSrc": "/images/events/IMG-20241116-WA0463.jpg",
    "alt": "Quant-A-Maze event photo 38",
    "width": 3024,
    "height": 4032
  },
  {
    "id": "event-photo-39",
    "src": "/images/events/thumbs/IMG-20241116-WA0487.webp",
    "originalSrc": "/images/events/IMG-20241116-WA0487.jpg",
    "alt": "Quant-A-Maze event photo 39",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-40",
    "src": "/images/events/thumbs/IMG-20241116-WA0493.webp",
    "originalSrc": "/images/events/IMG-20241116-WA0493.jpg",
    "alt": "Quant-A-Maze event photo 40",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-41",
    "src": "/images/events/thumbs/IMG-20241116-WA0495.webp",
    "originalSrc": "/images/events/IMG-20241116-WA0495.jpg",
    "alt": "Quant-A-Maze event photo 41",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-42",
    "src": "/images/events/thumbs/IMG-20241116-WA0495(1).webp",
    "originalSrc": "/images/events/IMG-20241116-WA0495(1).jpg",
    "alt": "Quant-A-Maze event photo 42",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-43",
    "src": "/images/events/thumbs/IMG-20241116-WA0495(1)(1).webp",
    "originalSrc": "/images/events/IMG-20241116-WA0495(1)(1).jpg",
    "alt": "Quant-A-Maze event photo 43",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-44",
    "src": "/images/events/thumbs/IMG-20241116-WA0495(1)(2).webp",
    "originalSrc": "/images/events/IMG-20241116-WA0495(1)(2).jpg",
    "alt": "Quant-A-Maze event photo 44",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-45",
    "src": "/images/events/thumbs/IMG-20241116-WA0499.webp",
    "originalSrc": "/images/events/IMG-20241116-WA0499.jpg",
    "alt": "Quant-A-Maze event photo 45",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-46",
    "src": "/images/events/thumbs/IMG-20241116-WA0503.webp",
    "originalSrc": "/images/events/IMG-20241116-WA0503.jpg",
    "alt": "Quant-A-Maze event photo 46",
    "width": 3840,
    "height": 2160
  },
  {
    "id": "event-photo-47",
    "src": "/images/events/thumbs/IMG-20241116-WA0509.webp",
    "originalSrc": "/images/events/IMG-20241116-WA0509.jpg",
    "alt": "Quant-A-Maze event photo 47",
    "width": 3840,
    "height": 2160
  },
  {
    "id": "event-photo-48",
    "src": "/images/events/thumbs/IMG-20241116-WA0525.webp",
    "originalSrc": "/images/events/IMG-20241116-WA0525.jpg",
    "alt": "Quant-A-Maze event photo 48",
    "width": 3840,
    "height": 2160
  },
  {
    "id": "event-photo-49",
    "src": "/images/events/thumbs/IMG-20241116-WA0529.webp",
    "originalSrc": "/images/events/IMG-20241116-WA0529.jpg",
    "alt": "Quant-A-Maze event photo 49",
    "width": 3024,
    "height": 4032
  },
  {
    "id": "event-photo-50",
    "src": "/images/events/thumbs/IMG-20241116-WA0529(1).webp",
    "originalSrc": "/images/events/IMG-20241116-WA0529(1).jpg",
    "alt": "Quant-A-Maze event photo 50",
    "width": 3024,
    "height": 4032
  },
  {
    "id": "event-photo-51",
    "src": "/images/events/thumbs/IMG-20241116-WA0531.webp",
    "originalSrc": "/images/events/IMG-20241116-WA0531.jpg",
    "alt": "Quant-A-Maze event photo 51",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-52",
    "src": "/images/events/thumbs/IMG-20241116-WA0533.webp",
    "originalSrc": "/images/events/IMG-20241116-WA0533.jpg",
    "alt": "Quant-A-Maze event photo 52",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-53",
    "src": "/images/events/thumbs/IMG-20241116-WA0535.webp",
    "originalSrc": "/images/events/IMG-20241116-WA0535.jpg",
    "alt": "Quant-A-Maze event photo 53",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-54",
    "src": "/images/events/thumbs/IMG-20241116-WA0535(1).webp",
    "originalSrc": "/images/events/IMG-20241116-WA0535(1).jpg",
    "alt": "Quant-A-Maze event photo 54",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-55",
    "src": "/images/events/thumbs/IMG-20241116-WA0535(1)(1).webp",
    "originalSrc": "/images/events/IMG-20241116-WA0535(1)(1).jpg",
    "alt": "Quant-A-Maze event photo 55",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-56",
    "src": "/images/events/thumbs/IMG-20241116-WA0535(1)(2).webp",
    "originalSrc": "/images/events/IMG-20241116-WA0535(1)(2).jpg",
    "alt": "Quant-A-Maze event photo 56",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-57",
    "src": "/images/events/thumbs/IMG-20241116-WA0580.webp",
    "originalSrc": "/images/events/IMG-20241116-WA0580.jpg",
    "alt": "Quant-A-Maze event photo 57",
    "width": 3024,
    "height": 4032
  },
  {
    "id": "event-photo-58",
    "src": "/images/events/thumbs/IMG-20241116-WA0618(1).webp",
    "originalSrc": "/images/events/IMG-20241116-WA0618(1).jpg",
    "alt": "Quant-A-Maze event photo 58",
    "width": 3840,
    "height": 2160
  },
  {
    "id": "event-photo-59",
    "src": "/images/events/thumbs/IMG-20241116-WA0864.webp",
    "originalSrc": "/images/events/IMG-20241116-WA0864.jpg",
    "alt": "Quant-A-Maze event photo 59",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-60",
    "src": "/images/events/thumbs/IMG-20241116-WA0864(1).webp",
    "originalSrc": "/images/events/IMG-20241116-WA0864(1).jpg",
    "alt": "Quant-A-Maze event photo 60",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-61",
    "src": "/images/events/thumbs/IMG-20241116-WA1115.webp",
    "originalSrc": "/images/events/IMG-20241116-WA1115.jpg",
    "alt": "Quant-A-Maze event photo 61",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-62",
    "src": "/images/events/thumbs/IMG-20241116-WA1254.webp",
    "originalSrc": "/images/events/IMG-20241116-WA1254.jpg",
    "alt": "Quant-A-Maze event photo 62",
    "width": 3024,
    "height": 4032
  },
  {
    "id": "event-photo-63",
    "src": "/images/events/thumbs/IMG-20241117-WA0033.webp",
    "originalSrc": "/images/events/IMG-20241117-WA0033.jpg",
    "alt": "Quant-A-Maze event photo 63",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-64",
    "src": "/images/events/thumbs/IMG-20241117-WA0033(1).webp",
    "originalSrc": "/images/events/IMG-20241117-WA0033(1).jpg",
    "alt": "Quant-A-Maze event photo 64",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-65",
    "src": "/images/events/thumbs/IMG-20241117-WA0039.webp",
    "originalSrc": "/images/events/IMG-20241117-WA0039.jpg",
    "alt": "Quant-A-Maze event photo 65",
    "width": 3024,
    "height": 4032
  },
  {
    "id": "event-photo-66",
    "src": "/images/events/thumbs/IMG-20241117-WA0090.webp",
    "originalSrc": "/images/events/IMG-20241117-WA0090.jpg",
    "alt": "Quant-A-Maze event photo 66",
    "width": 1280,
    "height": 853
  },
  {
    "id": "event-photo-67",
    "src": "/images/events/thumbs/IMG-20241117-WA0091.webp",
    "originalSrc": "/images/events/IMG-20241117-WA0091.jpg",
    "alt": "Quant-A-Maze event photo 67",
    "width": 1280,
    "height": 853
  },
  {
    "id": "event-photo-68",
    "src": "/images/events/thumbs/IMG-20241117-WA0099.webp",
    "originalSrc": "/images/events/IMG-20241117-WA0099.jpg",
    "alt": "Quant-A-Maze event photo 68",
    "width": 1280,
    "height": 512
  },
  {
    "id": "event-photo-69",
    "src": "/images/events/thumbs/IMG-20241117-WA0130.webp",
    "originalSrc": "/images/events/IMG-20241117-WA0130.jpg",
    "alt": "Quant-A-Maze event photo 69",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-70",
    "src": "/images/events/thumbs/IMG-20241117-WA0130(1).webp",
    "originalSrc": "/images/events/IMG-20241117-WA0130(1).jpg",
    "alt": "Quant-A-Maze event photo 70",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-71",
    "src": "/images/events/thumbs/IMG-20241117-WA0144.webp",
    "originalSrc": "/images/events/IMG-20241117-WA0144.jpg",
    "alt": "Quant-A-Maze event photo 71",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-72",
    "src": "/images/events/thumbs/IMG-20241117-WA0146.webp",
    "originalSrc": "/images/events/IMG-20241117-WA0146.jpg",
    "alt": "Quant-A-Maze event photo 72",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-73",
    "src": "/images/events/thumbs/IMG-20241117-WA0337.webp",
    "originalSrc": "/images/events/IMG-20241117-WA0337.jpg",
    "alt": "Quant-A-Maze event photo 73",
    "width": 4032,
    "height": 3024
  },
  {
    "id": "event-photo-74",
    "src": "/images/events/thumbs/IMG20241114103211.webp",
    "originalSrc": "/images/events/IMG20241114103211.jpg",
    "alt": "Quant-A-Maze event photo 74",
    "width": 3072,
    "height": 4096
  },
  {
    "id": "event-photo-75",
    "src": "/images/events/thumbs/IMG20241114103227.webp",
    "originalSrc": "/images/events/IMG20241114103227.jpg",
    "alt": "Quant-A-Maze event photo 75",
    "width": 3072,
    "height": 4096
  },
  {
    "id": "event-photo-76",
    "src": "/images/events/thumbs/IMG20241114142622.webp",
    "originalSrc": "/images/events/IMG20241114142622.jpg",
    "alt": "Quant-A-Maze event photo 76",
    "width": 3072,
    "height": 4096
  },
  {
    "id": "event-photo-77",
    "src": "/images/events/thumbs/IMG20241114142626_01.webp",
    "originalSrc": "/images/events/IMG20241114142626_01.jpg",
    "alt": "Quant-A-Maze event photo 77",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "event-photo-78",
    "src": "/images/events/thumbs/IMG20241114142626_01(1).webp",
    "originalSrc": "/images/events/IMG20241114142626_01(1).jpg",
    "alt": "Quant-A-Maze event photo 78",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "event-photo-79",
    "src": "/images/events/thumbs/IMG20241114151620_01.webp",
    "originalSrc": "/images/events/IMG20241114151620_01.jpg",
    "alt": "Quant-A-Maze event photo 79",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "event-photo-80",
    "src": "/images/events/thumbs/IMG20241114151620_01(1).webp",
    "originalSrc": "/images/events/IMG20241114151620_01(1).jpg",
    "alt": "Quant-A-Maze event photo 80",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "event-photo-81",
    "src": "/images/events/thumbs/IMG20241114152351_01.webp",
    "originalSrc": "/images/events/IMG20241114152351_01.jpg",
    "alt": "Quant-A-Maze event photo 81",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "event-photo-82",
    "src": "/images/events/thumbs/IMG20241114152351_01(1).webp",
    "originalSrc": "/images/events/IMG20241114152351_01(1).jpg",
    "alt": "Quant-A-Maze event photo 82",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "event-photo-83",
    "src": "/images/events/thumbs/IMG20241114152353_01.webp",
    "originalSrc": "/images/events/IMG20241114152353_01.jpg",
    "alt": "Quant-A-Maze event photo 83",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "event-photo-84",
    "src": "/images/events/thumbs/IMG20241114152358_01.webp",
    "originalSrc": "/images/events/IMG20241114152358_01.jpg",
    "alt": "Quant-A-Maze event photo 84",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "event-photo-85",
    "src": "/images/events/thumbs/IMG20241114152358_01(1).webp",
    "originalSrc": "/images/events/IMG20241114152358_01(1).jpg",
    "alt": "Quant-A-Maze event photo 85",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "event-photo-86",
    "src": "/images/events/thumbs/IMG20241114152358_01(2).webp",
    "originalSrc": "/images/events/IMG20241114152358_01(2).jpg",
    "alt": "Quant-A-Maze event photo 86",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "event-photo-87",
    "src": "/images/events/thumbs/IMG20241114152358_01(3).webp",
    "originalSrc": "/images/events/IMG20241114152358_01(3).jpg",
    "alt": "Quant-A-Maze event photo 87",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "event-photo-88",
    "src": "/images/events/thumbs/IMG20241114152514.webp",
    "originalSrc": "/images/events/IMG20241114152514.jpg",
    "alt": "Quant-A-Maze event photo 88",
    "width": 4096,
    "height": 3072
  },
  {
    "id": "event-photo-89",
    "src": "/images/events/thumbs/IMG20241114152514(1).webp",
    "originalSrc": "/images/events/IMG20241114152514(1).jpg",
    "alt": "Quant-A-Maze event photo 89",
    "width": 4096,
    "height": 3072
  },
  {
    "id": "event-photo-90",
    "src": "/images/events/thumbs/IMG20241114152600.webp",
    "originalSrc": "/images/events/IMG20241114152600.jpg",
    "alt": "Quant-A-Maze event photo 90",
    "width": 3072,
    "height": 4096
  },
  {
    "id": "event-photo-91",
    "src": "/images/events/thumbs/IMG20241114152600(1).webp",
    "originalSrc": "/images/events/IMG20241114152600(1).jpg",
    "alt": "Quant-A-Maze event photo 91",
    "width": 3072,
    "height": 4096
  },
  {
    "id": "event-photo-92",
    "src": "/images/events/thumbs/IMG20241114152600(2).webp",
    "originalSrc": "/images/events/IMG20241114152600(2).jpg",
    "alt": "Quant-A-Maze event photo 92",
    "width": 3072,
    "height": 4096
  },
  {
    "id": "event-photo-93",
    "src": "/images/events/thumbs/IMG20241114152600(3).webp",
    "originalSrc": "/images/events/IMG20241114152600(3).jpg",
    "alt": "Quant-A-Maze event photo 93",
    "width": 3072,
    "height": 4096
  },
  {
    "id": "event-photo-94",
    "src": "/images/events/thumbs/IMG20241114165654_01.webp",
    "originalSrc": "/images/events/IMG20241114165654_01.jpg",
    "alt": "Quant-A-Maze event photo 94",
    "width": 1920,
    "height": 1080
  },
  {
    "id": "event-photo-95",
    "src": "/images/events/thumbs/IMG20241114165654_01(1).webp",
    "originalSrc": "/images/events/IMG20241114165654_01(1).jpg",
    "alt": "Quant-A-Maze event photo 95",
    "width": 1920,
    "height": 1080
  },
  {
    "id": "event-photo-96",
    "src": "/images/events/thumbs/IMG20241114165703_01.webp",
    "originalSrc": "/images/events/IMG20241114165703_01.jpg",
    "alt": "Quant-A-Maze event photo 96",
    "width": 1920,
    "height": 1080
  },
  {
    "id": "event-photo-97",
    "src": "/images/events/thumbs/IMG20241114165703_01(1).webp",
    "originalSrc": "/images/events/IMG20241114165703_01(1).jpg",
    "alt": "Quant-A-Maze event photo 97",
    "width": 1920,
    "height": 1080
  },
  {
    "id": "event-photo-98",
    "src": "/images/events/thumbs/IMG20241114165712_01.webp",
    "originalSrc": "/images/events/IMG20241114165712_01.jpg",
    "alt": "Quant-A-Maze event photo 98",
    "width": 1920,
    "height": 1080
  },
  {
    "id": "event-photo-99",
    "src": "/images/events/thumbs/IMG20241114165712_01(1).webp",
    "originalSrc": "/images/events/IMG20241114165712_01(1).jpg",
    "alt": "Quant-A-Maze event photo 99",
    "width": 1920,
    "height": 1080
  },
  {
    "id": "event-photo-100",
    "src": "/images/events/thumbs/IMG20241114165953.webp",
    "originalSrc": "/images/events/IMG20241114165953.jpg",
    "alt": "Quant-A-Maze event photo 100",
    "width": 3072,
    "height": 4096
  },
  {
    "id": "event-photo-101",
    "src": "/images/events/thumbs/IMG20241114165953(1).webp",
    "originalSrc": "/images/events/IMG20241114165953(1).jpg",
    "alt": "Quant-A-Maze event photo 101",
    "width": 3072,
    "height": 4096
  },
  {
    "id": "event-photo-102",
    "src": "/images/events/thumbs/IMG20241114170002.webp",
    "originalSrc": "/images/events/IMG20241114170002.jpg",
    "alt": "Quant-A-Maze event photo 102",
    "width": 3072,
    "height": 4096
  },
  {
    "id": "event-photo-103",
    "src": "/images/events/thumbs/IMG20241114170002(1).webp",
    "originalSrc": "/images/events/IMG20241114170002(1).jpg",
    "alt": "Quant-A-Maze event photo 103",
    "width": 3072,
    "height": 4096
  },
  {
    "id": "event-photo-104",
    "src": "/images/events/thumbs/IMG20241114170419.webp",
    "originalSrc": "/images/events/IMG20241114170419.jpg",
    "alt": "Quant-A-Maze event photo 104",
    "width": 3072,
    "height": 4096
  },
  {
    "id": "event-photo-105",
    "src": "/images/events/thumbs/IMG20241114204845_01.webp",
    "originalSrc": "/images/events/IMG20241114204845_01.jpg",
    "alt": "Quant-A-Maze event photo 105",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "event-photo-106",
    "src": "/images/events/thumbs/IMG20241114204845_01(1).webp",
    "originalSrc": "/images/events/IMG20241114204845_01(1).jpg",
    "alt": "Quant-A-Maze event photo 106",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "event-photo-107",
    "src": "/images/events/thumbs/IMG20241114204845_03.webp",
    "originalSrc": "/images/events/IMG20241114204845_03.jpg",
    "alt": "Quant-A-Maze event photo 107",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "event-photo-108",
    "src": "/images/events/thumbs/IMG20241114204845_03(1).webp",
    "originalSrc": "/images/events/IMG20241114204845_03(1).jpg",
    "alt": "Quant-A-Maze event photo 108",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "event-photo-109",
    "src": "/images/events/thumbs/IMG20241115004951.webp",
    "originalSrc": "/images/events/IMG20241115004951.jpg",
    "alt": "Quant-A-Maze event photo 109",
    "width": 4096,
    "height": 3072
  },
  {
    "id": "event-photo-110",
    "src": "/images/events/thumbs/IMG20241116095328.webp",
    "originalSrc": "/images/events/IMG20241116095328.jpg",
    "alt": "Quant-A-Maze event photo 110",
    "width": 3072,
    "height": 4096
  },
  {
    "id": "event-photo-111",
    "src": "/images/events/thumbs/IMG20241116101929.webp",
    "originalSrc": "/images/events/IMG20241116101929.jpg",
    "alt": "Quant-A-Maze event photo 111",
    "width": 6144,
    "height": 8192
  },
  {
    "id": "event-photo-112",
    "src": "/images/events/thumbs/IMG20241116102644.webp",
    "originalSrc": "/images/events/IMG20241116102644.jpg",
    "alt": "Quant-A-Maze event photo 112",
    "width": 4096,
    "height": 3072
  },
  {
    "id": "event-photo-113",
    "src": "/images/events/thumbs/IMG20241116102644(1).webp",
    "originalSrc": "/images/events/IMG20241116102644(1).jpg",
    "alt": "Quant-A-Maze event photo 113",
    "width": 4096,
    "height": 3072
  },
  {
    "id": "event-photo-114",
    "src": "/images/events/thumbs/IMG20241116102648.webp",
    "originalSrc": "/images/events/IMG20241116102648.jpg",
    "alt": "Quant-A-Maze event photo 114",
    "width": 3072,
    "height": 4096
  },
  {
    "id": "event-photo-115",
    "src": "/images/events/thumbs/IMG20241116102648(1).webp",
    "originalSrc": "/images/events/IMG20241116102648(1).jpg",
    "alt": "Quant-A-Maze event photo 115",
    "width": 3072,
    "height": 4096
  },
  {
    "id": "event-photo-116",
    "src": "/images/events/thumbs/IMG20241116102651.webp",
    "originalSrc": "/images/events/IMG20241116102651.jpg",
    "alt": "Quant-A-Maze event photo 116",
    "width": 3072,
    "height": 4096
  },
  {
    "id": "event-photo-117",
    "src": "/images/events/thumbs/IMG20241116102651(1).webp",
    "originalSrc": "/images/events/IMG20241116102651(1).jpg",
    "alt": "Quant-A-Maze event photo 117",
    "width": 3072,
    "height": 4096
  },
  {
    "id": "event-photo-118",
    "src": "/images/events/thumbs/IMG20241116145725.webp",
    "originalSrc": "/images/events/IMG20241116145725.jpg",
    "alt": "Quant-A-Maze event photo 118",
    "width": 3072,
    "height": 4096
  },
  {
    "id": "event-photo-119",
    "src": "/images/events/thumbs/PXL_20241114_101751485.webp",
    "originalSrc": "/images/events/PXL_20241114_101751485.jpg",
    "alt": "Quant-A-Maze event photo 119",
    "width": 4080,
    "height": 3072
  },
  {
    "id": "event-photo-120",
    "src": "/images/events/thumbs/Snapchat-328104046.webp",
    "originalSrc": "/images/events/Snapchat-328104046.jpg",
    "alt": "Quant-A-Maze event photo 120",
    "width": 1836,
    "height": 3256
  },
  {
    "id": "event-photo-121",
    "src": "/images/events/thumbs/Snapchat-328104046(1).webp",
    "originalSrc": "/images/events/Snapchat-328104046(1).jpg",
    "alt": "Quant-A-Maze event photo 121",
    "width": 1836,
    "height": 3256
  },
  {
    "id": "event-photo-122",
    "src": "/images/events/thumbs/WhatsApp%20Image%202024-11-14%20at%2010.38.28_67e77809.webp",
    "originalSrc": "/images/events/WhatsApp%20Image%202024-11-14%20at%2010.38.28_67e77809.jpg",
    "alt": "Quant-A-Maze event photo 122",
    "width": 1280,
    "height": 963
  },
  {
    "id": "event-photo-123",
    "src": "/images/events/thumbs/WhatsApp%20Image%202024-11-15%20at%2004.17.42_a5433a01.webp",
    "originalSrc": "/images/events/WhatsApp%20Image%202024-11-15%20at%2004.17.42_a5433a01.jpg",
    "alt": "Quant-A-Maze event photo 123",
    "width": 721,
    "height": 1280
  },
  {
    "id": "event-photo-124",
    "src": "/images/events/thumbs/WhatsApp%20Image%202024-11-15%20at%2012.53.41_2be0eb49.webp",
    "originalSrc": "/images/events/WhatsApp%20Image%202024-11-15%20at%2012.53.41_2be0eb49.jpg",
    "alt": "Quant-A-Maze event photo 124",
    "width": 1152,
    "height": 864
  },
  {
    "id": "event-photo-125",
    "src": "/images/events/thumbs/WhatsApp%20Image%202024-11-15%20at%2012.53.41_96af226d.webp",
    "originalSrc": "/images/events/WhatsApp%20Image%202024-11-15%20at%2012.53.41_96af226d.jpg",
    "alt": "Quant-A-Maze event photo 125",
    "width": 864,
    "height": 1152
  },
  {
    "id": "event-photo-126",
    "src": "/images/events/thumbs/WhatsApp%20Image%202024-11-16%20at%2009.56.02_1059f7e2.webp",
    "originalSrc": "/images/events/WhatsApp%20Image%202024-11-16%20at%2009.56.02_1059f7e2.jpg",
    "alt": "Quant-A-Maze event photo 126",
    "width": 4096,
    "height": 3072
  },
  {
    "id": "event-photo-127",
    "src": "/images/events/thumbs/WhatsApp%20Image%202024-11-16%20at%2011.33.21_1e74b06f.webp",
    "originalSrc": "/images/events/WhatsApp%20Image%202024-11-16%20at%2011.33.21_1e74b06f.jpg",
    "alt": "Quant-A-Maze event photo 127",
    "width": 1152,
    "height": 864
  }
];
